name: testind flow

on: push
   
jobs:
    sampath:
        runs-on: ubuntu-latest
          
        steps:
            - name: hello display
              run: echo "hello dschl"
        
            - name: display the date
              run: date   
   
       