name: repovars and secret
on: workflow_dispatch
jobs:
   demo:
     runs_on: ubuntu_latest
     steps:
       -name:show repository variables
         run:echo"company is ${{vars.company}}"
         -name:secret repository
           env:
           rrr:{{secret.api_key}}
           run:"secret is":$rre
          -name:secret repository
           env:
           aaa:{{secret.password}}
           run:"secret is":$aaa
