-name:workflow-system
on:workflow_dispatch
jobs1 :
_ uses: actions/checkout@v5

-mame:build-stage
steps:
runs-on:ubuntu-latest
-name:create the file
RUN:echo "hello baby"
RUN:devops.txt
jobs2:
needs-on:build-stage
-name:run-stage
steps:
RUN:echo "rajareddy"
run:./java.txt
