name:declare vais
on:workflow_dispatch:
jobs:
    job A:
    runs-on:ubuntu-latest
    steps:
        env:
          country:india
          religion:hindu
      run:|
      echo"country is $country
      echo"religion is $religion
   steps2:
   run:|
      echo"country is $country
      echo"religion is $religion 
   
      

